Exercice 1 : Introduction to Data Analysis (Essay) What is Data Analysis? Data analysis is the process of inspecting, cleaning, transforming, and modeling data to discover useful information, support decision-making, and identify patterns or trends. Why is it important in modern contexts? Prise de décision basée sur les faits : Réduit l’incertitude et le risque. Avantage compétitif : Permet la personnalisation (Netflix, Amazon), l’optimisation opérationnelle et la prédiction. Impact sociétal : Santé publique, lutte contre le changement climatique, détection de fraudes. Croissance exponentielle des données : Avec le Big Data, l’IA et le Machine Learning, l’analyse est devenue indispensable. Trois domaines d’application actuels : Santé : Analyse prédictive des épidémies, personnalisation des traitements (ex. : modèles COVID-19). Finance : Détection de fraudes, scoring crédit, trading algorithmique. Marketing / E-commerce : Recommandation de produits, segmentation clients, analyse de sentiment sur les réseaux sociaux. Conseil pro : Toujours lier l’analyse aux objectifs métier (Business Question → Data → Insight → Action).

Exercice 2 : Dataset Loading and Initial Analysis Datasets mentionnés : How Much Sleep Do Americans Really Get? Global Trends in Mental Health Disorder Credit Card Approvals Code professionnel (Google Colab / Jupyter) :

In [9]:
import pandas as pd

# 1. Sleep dataset (exemple Kaggle)
sleep_url = "https://raw.githubusercontent.com/.../sleep_americans.csv"  # Remplace par le vrai lien ou utilise Kaggle API
sleep = pd.read_csv("HowMuchSleep.csv")  # ou pd.read_csv(uploaded file)
print("=== Sleep Dataset ===")
print(sleep.head())
print(sleep.info())
print(sleep.describe())

# 2. Mental Health
mental = pd.read_csv("mental_health_global.csv")
print("\n=== Mental Health ===")
print(mental.head())

# 3. Credit Card Approvals
credit = pd.read_csv("credit_approval.csv")
print("\n=== Credit Card ===")
print(credit.head())

Data loaded successfully! Here's a preview of the dataset:

,Date,Time,Location,Operator,Flight #,Route,Type,Registration,cn/In,Aboard,Fatalities,Ground,Summary
0,09/17/1908,17:18,"Fort Myer, Virginia",Military - U.S. Army,NaN,Demonstration,Wright Flyer III,NaN,1,2.0,1.0,0.0,"During a demonstration flight, a U.S. Army fly..."
1,07/12/1912,06:30,"AtlantiCity, New Jersey",Military - U.S. Navy,NaN,Test flight,Dirigible,NaN,NaN,5.0,5.0,0.0,First U.S. dirigible Akron exploded just offsh...
2,08/06/1913,NaN,"Victoria, British Columbia, Canada",Private,-,NaN,Curtiss seaplane,NaN,NaN,1.0,1.0,0.0,The first fatal airplane accident in Canada oc...
3,09/09/1913,18:30,Over the North Sea,Military - German Navy,NaN,NaN,Zeppelin L-1 (airship),NaN,NaN,20.0,14.0,0.0,The airship flew into a thunderstorm and encou...
4,10/17/1913,10:30,"Near Johannisthal, Germany",Military - German Navy,NaN,NaN,Zeppelin L-2 (airship),NaN,NaN,30.0,30.0,0.0,Hydrogen gas which was being vented was sucked...

Initial DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5268 entries, 0 to 5267
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          5268 non-null   object
 1   Time          3049 non-null   object
 2   Location      5248 non-null   object
 3   Operator      5250 non-null   object
 4   Flight #      1069 non-null   object
 5   Route         3561 non-null   object
 6   Type          5241 non-null   object
 7   Registration  4933 non-null   object
 8   cn/In         4040 non-null   object
 9   Aboard        5246 non-null   float64
 10  Fatalities    5256 non-null   float64
 11  Ground        5246 non-null   float64
 12  Summary       4878 non-null   object
dtypes: float64(3), object(10)
memory usage: 535.2+ KB

Missing values before cleaning:

Date               0
Time            2219
Location          20
Operator          18
Flight #        4199
Route           1707
Type              27
Registration     335
cn/In           1228
Aboard            22
Fatalities        12
Ground            22
Summary          390
dtype: int64

DataFrame Info after initial cleaning and type conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5268 entries, 0 to 5267
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              5268 non-null   datetime64[ns]
 1   Time              3049 non-null   object
 2   Location          5248 non-null   object
 3   Operator          5250 non-null   object
 4   Flight #          1069 non-null   object
 5   Route             3561 non-null   object
 6   Type              5241 non-null   object
 7   Registration      4933 non-null   object
 8   cn/In             4040 non-null   object
 9   Aboard            5268 non-null   int64
 10  Fatalities        5268 non-null   int64
 11  Ground            5268 non-null   int64
 12  Summary           4878 non-null   object
 13  Year              5268 non-null   int32
 14  DateTime          5255 non-null   datetime64[ns]
 15  Total_Fatalities  5268 non-null   int64
dtypes: datetime64[ns](2), int32(1), int64(4), object(9)
memory usage: 638.1+ KB

Missing values after initial cleaning:

Date                   0
Time                2219
Location              20
Operator              18
Flight #            4199
Route               1707
Type                  27
Registration         335
cn/In               1228
Aboard                 0
Fatalities             0
Ground                 0
Summary              390
Year                   0
DateTime              13
Total_Fatalities       0
dtype: int64

Description brève :
Sleep : Données temporelles par âge, sexe, activité → quantitative majoritaire.
Mental Health : Prévalence % par pays et année → séries temporelles.
Credit : Données de candidature (démographiques + financières) pour prédiction binaire.

(Exercice 3)

**1. Sleep Dataset**

*   **`Age group`, `Sex`**
    *   **Type :** Qualitative (Nominale/Ordinale, selon la granularité de l'âge)
    *   **Justification :** Catégories pour regrouper les individus. L'âge peut être ordinal si les groupes sont ordonnés (ex: '20-30', '30-40').
*   **`Avg hrs per day sleeping`, `Activity`**
    *   **Type :** Quantitative (Continue)
    *   **Justification :** Mesures numériques d'heures et de niveaux d'activité, qui peuvent avoir des valeurs décimales.

**2. Mental Health Dataset**

*   **`Entity`, `Code`**
    *   **Type :** Qualitative (Nominale)
    *   **Justification :** Identifiants textuels ou alphanumériques qui classifient sans ordre.
*   **`Year`**
    *   **Type :** Quantitative (Discrète)
    *   **Justification :** Nombres entiers représentant des points spécifiques dans le temps.
*   **`% disorders (Schizophrenia, Depression...)`**
    *   **Type :** Quantitative (Continue)
    *   **Justification :** Pourcentages qui peuvent prendre n'importe quelle valeur décimale entre 0 et 100.

**3. Credit Card Approvals Dataset**

*   **`Gender`, `Married`, `Education`**
    *   **Type :** Qualitative (Nominale)
    *   **Justification :** Catégories descriptives sans ordre numérique.
*   **`Age`, `Income`, `Credit Amount`**
    *   **Type :** Quantitative (Continue ou Discrète, selon la précision des données)
    *   **Justification :** Mesures numériques liées aux attributs financiers et démographiques.

Exercise 4: Exploring Data Types

In [19]:
print("Iris Dataset - First 5 rows:")
display(iris.head())

print("\nIris Dataset - Data types:")
display(iris.dtypes)

Iris Dataset - First 5 rows:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Iris Dataset - Data types:

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

Exercise 5: Basic Observation Skills in Data Analysis

### Exercise 5: Basic Observation Skills in Data Analysis

We will now load the 'How Much Sleep Do Americans Really Get?' dataset and proceed to identify columns that could be interesting for specific types of analysis.

In [21]:
import pandas as pd

# Load the 'How Much Sleep Do Americans Really Get?' dataset.
# Based on previous interactions, 'HowMuchSleep.csv' might be a local file.
# If it's not available locally, you might need to upload it or provide a direct URL.
try:
    sleep_df = pd.read_csv('HowMuchSleep.csv')
    print("Sleep Dataset loaded successfully!")
    print("\nFirst 5 rows:")
    display(sleep_df.head())
    print("\nDataFrame Information:")
    display(sleep_df.info())
except FileNotFoundError:
    print("Error: 'HowMuchSleep.csv' not found. Please ensure the file is uploaded to your Colab environment or provide the correct path/URL.")
    print("If you have a URL, you can try loading it like: `sleep_df = pd.read_csv('YOUR_DATASET_URL_HERE')`")
    sleep_df = None # Set df to None to indicate it wasn't loaded

Error: 'HowMuchSleep.csv' not found. Please ensure the file is uploaded to your Colab environment or provide the correct path/URL.
If you have a URL, you can try loading it like: `sleep_df = pd.read_csv('YOUR_DATASET_URL_HERE')`

Exercise 6: Identifying Data Types

### Exercise 6: Identifying Data Types - Structured vs. Unstructured

To categorize these data sources, let's first define **structured** and **unstructured** data:

*   **Structured Data:** Data that has a predefined format and is organized in a fixed schema, typically tabular. It's easy to store, query, and analyze using conventional databases (e.g., relational databases).
    *   **Examples:** Database tables, Excel spreadsheets, CSV files with consistent columns.

*   **Unstructured Data:** Data that does not have a predefined format or organization. It can be textual or non-textual and often requires more advanced techniques (like natural language processing or machine learning) for analysis.
    *   **Examples:** Text documents, images, audio, video, social media posts.

---

#### Classification of Provided Data Sources:

1.  **A company’s financial reports stored in an Excel file.**
    *   **Classification:** Structured Data
    *   **Justification:** Excel files typically organize financial data into rows and columns with clear headers and data types (e.g., dates, numbers, text), fitting a predefined tabular schema.

2.  **Photographs uploaded to a social media platform.**
    *   **Classification:** Unstructured Data
    *   **Justification:** Photographs are visual media. While they might have metadata (like date, location, camera type), the core content of the image itself (pixels, objects, scenes) does not conform to a fixed, tabular structure.

3.  **A collection of news articles on a website.**
    *   **Classification:** Unstructured Data
    *   **Justification:** News articles are primarily text. Although they might have some structured elements like publication date or author, the main body of the text content is free-form and does not fit into a rigid, predefined data model.

4.  **Inventory data in a relational database.**
    *   **Classification:** Structured Data
    *   **Justification:** Relational databases are designed specifically to store and manage structured data. Inventory data would be organized into tables with columns for items, quantities, prices, locations, etc., all adhering to a strict schema.

5.  **Recorded interviews from a market research study.**
    *   **Classification:** Unstructured Data
    *   **Justification:** Recorded interviews are audio (or video) files. The content is spoken language, which is free-form and lacks a predefined tabular structure. Analyzing this would typically involve transcription and natural language processing.

Exercise 7: Transformation Exercise

### Exercise 7: Transformation Exercise - Converting Unstructured to Structured Data

This exercise focuses on understanding how various unstructured data sources can be transformed into structured formats, making them amenable to quantitative analysis and database storage.

---

#### Methods for Converting Unstructured Data to Structured Data:

1.  **A series of blog posts about travel experiences.**
    *   **Method:**
        1.  **Text Extraction & Cleaning:** Extract the raw text from each blog post. Remove HTML tags, advertisements, and irrelevant boilerplate text.
        2.  **Natural Language Processing (NLP):** Apply NLP techniques such as:
            *   **Named Entity Recognition (NER):** Identify and extract entities like locations (cities, countries), attractions, dates, and names of people/companies mentioned.
            *   **Sentiment Analysis:** Determine the emotional tone (positive, negative, neutral) of the travel experiences.
            *   **Topic Modeling:** Identify main themes or topics discussed in each post (e.g., 'adventure travel', 'beach holidays', 'cultural immersion').
            *   **Keyword Extraction:** Identify relevant keywords and phrases.
        3.  **Feature Extraction:** Extract quantitative features such as word count, reading time, number of images, number of comments.
    *   **Structured Output Examples:** A table with columns like `Post_ID`, `Title`, `Author`, `Publish_Date`, `Main_Location`, `Sentiment_Score`, `Dominant_Topic`, `Keywords`, `Word_Count`, `Avg_Rating` (if available).
    *   **Reasoning:** Blog posts are free-form text. NLP is essential to extract meaningful entities and sentiments, turning qualitative observations into quantifiable and categorizable data. This allows for analysis like 'What are the most positively reviewed travel destinations?', 'Which topics are most frequently discussed by travelers?', or 'How does post length correlate with engagement?'

2.  **Audio recordings of customer service calls.**
    *   **Method:**
        1.  **Speech-to-Text (STT) Transcription:** Convert the audio recordings into written transcripts.
        2.  **NLP on Transcripts:** Similar to blog posts, apply NLP:
            *   **Sentiment Analysis:** Assess customer satisfaction or frustration during the call.
            *   **Intent Recognition:** Identify the customer's purpose for calling (e.g., 'technical support', 'billing inquiry', 'product complaint').
            *   **Keyword/Phrase Detection:** Identify specific product names, common complaints, or resolution steps.
            *   **Entity Extraction:** Extract customer names, product IDs, order numbers.
        3.  **Acoustic Feature Extraction (Optional but valuable):** Analyze non-linguistic cues from the audio like pitch, volume, speaking rate, which can indicate emotional states.
    *   **Structured Output Examples:** A table with columns like `Call_ID`, `Date_Time`, `Customer_ID`, `Agent_ID`, `Call_Duration`, `Customer_Sentiment`, `Call_Intent`, `Keywords_Detected`, `Issue_Resolution_Status`.
    *   **Reasoning:** Audio is inherently unstructured. STT converts it to text, and then NLP can extract critical information about customer interactions, issues, and sentiment. This enables analysis such as 'What are the most common reasons for negative sentiment calls?', 'Which agents have the highest resolution rates for technical issues?', or 'How does call duration relate to customer satisfaction?'

3.  **Handwritten notes from a brainstorming session.**
    *   **Method:**
        1.  **Optical Character Recognition (OCR):** Use OCR technology to convert handwritten text into digital, machine-readable text.
        2.  **Keyword and Idea Extraction:** Manually or semi-automatically extract key ideas, concepts, and action items from the digitized text.
        3.  **Categorization/Tagging:** Group related ideas into categories or assign tags (e.g., 'marketing', 'product feature', 'risk', 'solution').
        4.  **Relationship Mapping:** Identify connections between ideas (e.g., 'idea X supports idea Y').
    *   **Structured Output Examples:** A table with columns like `Note_ID`, `Session_Date`, `Participant`, `Idea_Text`, `Category`, `Keywords`, `Related_Ideas`, `Action_Item` (boolean), `Priority`.
    *   **Reasoning:** Handwritten notes are highly unstructured. OCR provides the initial digitization. Subsequent manual or NLP-assisted extraction and categorization are needed to structure the qualitative content into actionable data. This helps in tracking brainstorming output, identifying key themes, prioritizing ideas, and assigning tasks.

4.  **A video tutorial on cooking.**
    *   **Method:**
        1.  **Video Segmentation:** Break down the video into logical segments (e.g., 'introduction', 'ingredient preparation', 'cooking step 1', 'plating').
        2.  **Speech-to-Text (STT) & NLP:** Transcribe spoken instructions and dialogue. Use NLP to extract:
            *   **Ingredients:** List all ingredients mentioned.
            *   **Cooking Steps:** Detail each instruction (e.g., 'chop onions', 'sauté for 5 minutes', 'bake at 350°F').
            *   **Tools/Equipment:** Identify kitchen tools used.
            *   **Time Durations:** Extract cooking times, prep times.
        3.  **Object Recognition (Computer Vision):** Use computer vision to identify objects in the video frames (e.g., 'knife', 'pot', 'carrot', 'finished dish').
        4.  **Action Recognition:** Identify cooking actions being performed (e.g., 'mixing', 'slicing', 'stirring').
        5.  **Metadata Extraction:** Extract video metadata like title, description, tags, upload date.
    *   **Structured Output Examples:** A table with columns like `Video_ID`, `Recipe_Name`, `Cuisine_Type`, `Total_Prep_Time`, `Total_Cook_Time`, `Key_Ingredients`, `Tools_Used`, `Complexity_Level`, `Step_by_Step_Instructions` (as a list or structured text), `Sentiment_Score` (from narration).
    *   **Reasoning:** Video is a rich, complex unstructured data type. Combining STT, NLP, and computer vision allows for comprehensive extraction of both auditory and visual information. This enables structured analysis such as 'What are the most common ingredients in quick recipes?', 'Which cooking techniques are frequently demonstrated?', or 'How long does an average recipe tutorial last?'

Exercise 8

### Exercise 8: Import a file from Kaggle (via GitHub for convenience)

We will now import the `train.csv` dataset directly from a GitHub repository as instructed and display its first few rows to verify the import.

In [22]:
import pandas as pd

# Define the URL for the train.csv dataset on GitHub
# Based on common Kaggle dataset hosting patterns on GitHub, a typical structure would be:
# https://raw.githubusercontent.com/user/repo/branch/path/to/file.csv
# I will use a common dataset source. If this is not the correct dataset, please provide the exact GitHub URL.
dataset_url = "https://raw.githubusercontent.com/plotly/datasets/master/train.csv"

try:
    # Load the train.csv file into a pandas DataFrame
    train_df = pd.read_csv(dataset_url)
    print(f"Dataset loaded successfully from: {dataset_url}")

    # Print the first few rows of the DataFrame
    print("\nFirst 5 rows of the train dataset:")
    display(train_df.head())

    # Display DataFrame information to check columns and data types
    print("\nDataFrame Information:")
    display(train_df.info())

except Exception as e:
    print(f"Error loading dataset: {e}")
    print("Please ensure the provided GitHub URL is correct and accessible.")
    train_df = None

Error loading dataset: HTTP Error 404: Not Found
Please ensure the provided GitHub URL is correct and accessible.

Exercise 9 : Export a dataframe to excel format and JSON format.

In [23]:
import pandas as pd

# Create a simple DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df_export = pd.DataFrame(data)

print("Original DataFrame:")
display(df_export)

Original DataFrame:

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston

In [24]:
# Export the DataFrame to an Excel file
excel_file_name = 'exported_dataframe.xlsx'
df_export.to_excel(excel_file_name, index=False)
print(f"DataFrame exported to {excel_file_name}")

DataFrame exported to exported_dataframe.xlsx

In [25]:
# Export the DataFrame to a JSON file
json_file_name = 'exported_dataframe.json'
df_export.to_json(json_file_name, orient='records', indent=4)
print(f"DataFrame exported to {json_file_name}")

DataFrame exported to exported_dataframe.json

Exercise 10: Reading JSON Data

In [27]:
# Using a sample JSON dataset URL
json_url = 'https://raw.githubusercontent.com/vega/vega-datasets/next/data/cars.json'

try:
    # Read the JSON data from the URL into a pandas DataFrame
    df_json = pd.read_json(json_url)
    print(f"JSON data loaded successfully from: {json_url}")

    # Display the first five entries of the DataFrame
    print("\nFirst 5 rows of the JSON dataset:")
    display(df_json.head())

    # Display DataFrame information to check columns and data types
    print("\nDataFrame Information:")
    display(df_json.info())

except Exception as e:
    print(f"Error loading JSON data: {e}")
    print("Please ensure the provided URL is correct and accessible.")
    df_json = None

JSON data loaded successfully from: https://raw.githubusercontent.com/vega/vega-datasets/next/data/cars.json

First 5 rows of the JSON dataset:

,Name,Miles_per_Gallon,Cylinders,Displacement,Horsepower,Weight_in_lbs,Acceleration,Year,Origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,1970-01-01,USA
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,1970-01-01,USA
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,1970-01-01,USA
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,1970-01-01,USA
4,ford torino,17.0,8,302.0,140.0,3449,10.5,1970-01-01,USA

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406 entries, 0 to 405
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              406 non-null    object
 1   Miles_per_Gallon  398 non-null    float64
 2   Cylinders         406 non-null    int64
 3   Displacement      406 non-null    float64
 4   Horsepower        400 non-null    float64
 5   Weight_in_lbs     406 non-null    int64
 6   Acceleration      406 non-null    float64
 7   Year              406 non-null    object
 8   Origin            406 non-null    object
dtypes: float64(4), int64(2), object(3)
memory usage: 28.7+ KB

None